name: deploy_frontend_folder_to_blob

on:
    push:
        branches: [ main ]
        paths:
        - 'fronted/**'
        
permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name cypherscloudresume --auth-mode key -d '$web' -s ./frontend

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()